conexiones iniciales para TP0
sisoputnfrba/tp0 pull request #1
Opened 2019-03-05 17:09 UTC by gastoncastineira

Lo logré!
 
Les dejo un bonito PR con lo que hice, sobre todo las conexiones. Al main todavía le falta trabajo y faltan comentarios para que entiendan los alumnos qué hacer

2019-03-13 14:01 UTC, CMauro96 commented
![image](https://media.giphy.com/media/XreQmk7ETCak0/giphy.gif)

2019-03-16 00:10 UTC, tferraro requested changes
Buenas! Eventualmente pude revisarlo, semanas dificiles 😆 

Buen laburo che! Le encontré un par de detalles que dejé para charlarlos y algunas cosas que me hicieron ruido respecto a lo que queremos transmitir 😥.

Cualquier cosa que algo no se entienda, lo vamos viendo 💪

2019-03-16 00:10 UTC, tferraro commented on Cliente/conexiones.c
> +	signal(SIGSEGV, (void*) segfault_handler);
Esta es más una pregunta, queremos handlear el SIGSERGV? No sirve la experiencia de haberla manqueado y ver un segmentation fault de primera mano?

En mi opinión, entre un Core-dump y un printf que *handlea la signal*, me quedo con el dump, por cuestiones de mantenibilidad y no tapar algún otro problema.

PD: No queremos enseñarles que esa signal se puede catchear xD

2019-03-16 00:10 UTC, tferraro commented on Cliente/Cliente.c
> +	while(clave[0] != '0')
Que implica el `'0'`? Cual es la razón por la que nuestra condición de corte es que el primer caracter sea "cero"?

2019-03-16 00:10 UTC, tferraro commented on Servidor/conexiones.h
> +static int g_socket_cliente;
Tratemos en lo posible, de evitar las variables globales. Las variables globales le restan legibilidad al código y generan side-effects.

Podemos aprovechar la línea con la que vienen de pdep, haciendo que las funciones sean "cajitas" que reciben A y devuelven B. Les puede aportar banda más que acostumbrarse a usar globales (que les van a cagar la vida durante el cuatri).

2019-03-16 00:10 UTC, tferraro commented on Servidor/conexiones.c
> +		exit(0);
Dos cosillas sobre esto que me llamaron la atención:
- exit(0) estaría demostrando que está todo ok. No querríamos demostrar error?
- Evitemos llamar a exit() desde lugares internos que maten al proceso. Te mata el uso de valgrind por los leaks y si los chicos adquieren esa práctica, la van a pasar mal 😕.

2019-03-16 00:10 UTC, tferraro commented on Cliente/conexiones.c
> +static void* serializar_paquete(t_paquete* paquete, int bytes)
Cual es el racional de poner las funciones como estáticas? Ocultarlas? Conviene poner un comentario con el racional de porque están estáticas en el código?

Quiero evitar que mechen `static` porque "en el codigo del tp0 lo pusieron" y evitarse el thread unsafe 😛

2019-03-16 02:13 UTC, gastoncastineira commented on Cliente/conexiones.c
> +	signal(SIGSEGV, (void*) segfault_handler);
Acá hay dos razones por la que eso está acá.

- Como la idea es traer una temática, parte de lo que hablamos en la charla es hacer un mensaje menos feo que _(core dumped) - segmentation fault_. Por ahora está el que está por estar y la idea a largo plazo es cambiarlo.

- Otra cosa que hablamos cuando nos juntamos es que sí queremos decirles que se puede catchear! Más que nada cuando ya están probando el TP o estamos en la entrega que les rompe algo y quedan 17 segundos esperando a que el SO les libere el puerto bindeado que nunca le hicieron close() (que ahora que me fijo yo me olvidé de hacerlo xD)

Si preferís, esto queda para charlarlo en la llamada cuando sea que quedemos en hacerla

2019-03-16 02:14 UTC, gastoncastineira commented on Cliente/Cliente.c
> +	while(clave[0] != '0')
Todo lo que está en ambos mains() está ahí nomás para que vean cómo lo probé y por si lo quieren probar ustedes. La idea es que el TP0 final no tenga nada de lo que hice ahí :p
Ahí particularmente por si te interesa saberlo, solo quería hacer una condición de corte para poder probar enviar mensajes y paquetes

2019-03-16 02:14 UTC, gastoncastineira commented on Servidor/conexiones.c
> +		exit(0);
Buen punto. Entre mañana y el lunes lo arreglo

2019-03-16 02:14 UTC, gastoncastineira commented on Cliente/conexiones.c
> +static void* serializar_paquete(t_paquete* paquete, int bytes)
¿Decís de borrar los static y los extern o poner un comentario explicando qué son y por qué se pusieron?
Me basé más que nada en algunos parsers viejos de la cátedra, porque hasta hace poco no sabía que existían y dije "bueno, por algo lo hicieron así" jajaja

2019-03-16 02:15 UTC, gastoncastineira commented on Servidor/conexiones.h
> +static int g_socket_cliente;
Coincido con el tema de las variables globales, pero como la idea de este TP0 es abstraerlos de toda la parte de sockets a los que vayan (porque sockets se ve en la segunda charla), resultaba imposible no hacer alguna global sin tener que hacer que todas las funciones tuvieran que recibir el socket. 
¿Decís de hacer que lo reciban igual?

2019-03-17 20:19 UTC, SofiCortes commented on Cliente/conexiones.c
> +static void* serializar_paquete(t_paquete* paquete, int bytes)
Concuerdo con lo de static. Los van a necesitar?

2019-03-18 00:15 UTC, tferraro commented on Cliente/conexiones.c
> +	signal(SIGSEGV, (void*) segfault_handler);
> Otra cosa que hablamos cuando nos juntamos es que sí queremos decirles que se puede catchear! Más que nada cuando ya están probando el TP o estamos en la entrega que les rompe algo y quedan 17 segundos esperando a que el SO les libere el puerto bindeado que nunca le hicieron close() (que ahora que me fijo yo me olvidé de hacerlo xD)

Siento que es usar una escopeta para matar un mosquito. No podríamos hacer un video al respecto y como liberar el puerto tomado y ya?

Por otro lado, +1 a verlo en un rato.

2019-03-18 00:17 UTC, tferraro commented on Servidor/conexiones.h
> +static int g_socket_cliente;
Yo creo que quiero el tradeoff de que vayan pispeando que onda los sockets, pero sin pelearse con la config y que significa cada cosa. Pero al menos que entiendan que la conexión se asocia a un "int" que es un "socket".

2019-03-18 00:18 UTC, tferraro commented on Cliente/conexiones.c
> +static void* serializar_paquete(t_paquete* paquete, int bytes)
> Me basé más que nada en algunos parsers viejos de la cátedra, porque hasta hace poco no sabía que existían y dije "bueno, por algo lo hicieron así" jajaja

Exactamente por esto no me está cerrando, no hay un racional de fondo 🙁 . Entonces evitemosnos esas keys a menos que sea estrictamente necesario

2019-03-19 23:31 UTC, tferraro commented
@gastoncastineira seguramente cambie un par de cosas para ajustarlos al formato del TP0, usalo como base.

2019-03-19 23:52 UTC, tferraro requested changes
De entrada necesitaríamos lo siguiente:
- Que el servidor esté separado y tengamos un script que lo compile y lo ejecute, que para los chicos sea transparente.
- Que no tengamos un "cliente", sinó un "tp0.c" y como mucho un par de "utils".
- Sacar las cosas hardcodeadas y poner comentarios en el "tp0.c" para que sepan donde completar.

2019-03-23 17:28 UTC, tferraro requested changes
Lo vi mucho mejor que el anterior! jajajaja

Le tiré un par de observaciones para hacerlo matchear con el docu del TP0 y hacer un poco más ameno el desarrollo.

Cualquier cosa lo vemos!

2019-03-23 17:28 UTC, tferraro commented on Cliente/makefile
> +# Como nos conviene armar un makefile?
Podemos tener todo lo del tp0 suelto? Y solo una carpeta server y adentro su propio makefile para correr el server?

2019-03-23 17:28 UTC, tferraro commented on Cliente/makefile
> +LIBS = -lcrypto -lcommons # Incluimos las bibliotecas que necesitamos, las commos y la biblio para el MD5
Entonces las commons ya las tenemos agregadas. Fue, agreguemos readline y listo.
Evitemonos que importen ellos las bibliotecas y en el peor de los casos, que aprendan con las guias que tenemos 🤷🏻‍♂️.

ib4: Pongamos un link a las guias o a los videos

2019-03-23 17:28 UTC, tferraro commented on Cliente/tp0.c
> +	//Loggeamelo
Guarda con esto, el enunciado está pensado para que vayan haciendo un for y ahí dentro hagan el agregar_a_ paquete.

Habría que pensar una manera de manejar bien el free con esto

2019-03-23 17:28 UTC, tferraro commented on Cliente/tp0.c
> +int conectar_cliente(t_config* config)
Queremos wrappear esto? Que directamente lo hagan ellos primero creando y dspues "conectando". No hace falta abstraer tanto en funciones, que lo hagan todo en el main y fue

2019-03-23 17:28 UTC, tferraro commented on Cliente/tp0.c
> +void enviar_clave(t_config* config, int conexion)
Idem arriba

2019-03-25 03:08 UTC, SofiCortes submitted a review, later dismissed

2019-03-25 03:08 UTC, SofiCortes commented on tp0.c
> +	t_log* logger;
Bueno, si dejamos el logger acá declarado acá, y seguimos los pasos del código comentado, se rompe la aplicación (mandé screenshot al grupo de wpp, acá no se como attachear imágenes). Tira invalid_pointer no sé y se rompe en el log_destroy. No me detuve a investigar porque sucede esto.
Con Adro vimos que en el servidor el logger está como variable global. En el tp cuatrimestral el logger seguramente lo usen como variable global. Si acá lo pasamos como variable global en el .h se soluciona el problema anterior, y además, ya ven como se usa para el tp.

2019-03-25 17:34 UTC, gastoncastineira commented on tp0.c
> +	t_log* logger;
arreglado, y el commit tiene un nombre apropiado para el error

2019-03-26 00:50 UTC, tferraro approved these changes
Groso! Tiré un par de suggestions, pero son re menores y se fixean rápido.

Si lo probaste siguiendo el docu y no hay discrepancias (compila de una y compilan y funcionan todos los entregables), pues dale merge nomás!

2019-03-26 00:50 UTC, tferraro commented on makefile
> +LIBS = -lreadline -lcommons # Incluimos las bibliotecas que necesitamos, las commos y la biblio para el MD5
Typo:
```suggestion
LIBS = -lreadline -lcommons # Incluimos las bibliotecas que necesitamos, las commos y readline
```

2019-03-26 00:50 UTC, tferraro commented on tp0.h
> +t_log* g_logger;
```suggestion
// Por lo general, a menos que tengan que tener recursos compartidos, no es buena práctica usar variables globales. Nosotros lo estamos haciendo por la simplicidad del TP0 :)
t_log* g_logger;
```

2019-03-26 00:50 UTC, tferraro commented on utils.h
> +t_paquete* crear_paquete(void);
```suggestion
t_paquete* crear_paquete(void);
t_paquete* crear_super_paquete(void);
```

2019-03-26 02:56 UTC, merged